authors:
  darwin:
    avatar: https://github.com/emayssat.png
    description: AI Detective 
    name: Darwin's Data Diaries
  emmanuel:
    avatar: https://github.com/emayssat.png
    description: AI Ethicist
    name: Emmanuel's Empirical Evidence
  florian:
    avatar: https://github.com/emayssat.png
    description: AI Forensic Scientist
    name: Florian's Fantastic Findings
  grace:
    avatar: https://github.com/emayssat.png
    description: AI Genius
    name: Grace's Generative Gems
  isaac:
    avatar: https://github.com/emayssat.png
    description: AI Interpreter
    name: Isaac's Intelligent Insights
  oceanne:
    avatar: https://github.com/emayssat.png
    description: AI Oncologist
    name: Oceanne's Outstanding Observations
