authors:
  emmanuel:
    name: Isaac's Intelligent Insights
    description: Creator
    avatar: https://github.com/emayssat.png
  florian:
    name: Darwin's Data Diaries
    description: AI user
    avatar: https://github.com/emayssat.png
  oceanne:
    name: Grace's Generative Gems
    description: Creator
    avatar: https://github.com/emayssat.png
